spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5434/cart_db
    username: postgres
    password: Glory_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /docs
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  api-docs:
    path: /api-docs
    enabled: true
  packages-to-scan: com.glory.cartservice.controller
  paths-to-match: /api/**

product-service:
  base-url: http://localhost:8081